import { Product, ProjectCaseStudy, Story } from "./types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    slug: "astra-halo-pendant",
    title: "Astra Halo Pendant Light",
    tagline: "Hand-burnished solid brass ring with diffused warm LED circumference.",
    description:
      "Engineered from heavy-gauge solid brass, the Astra Halo Pendant balances minimalist geometry with architectural presence. Each ring is individually hand-polished and sealed with a micro-thin satin lacquer to prevent tarnishing while highlighting the natural grain of the metal.",
    fixtureType: "Pendants",
    spatialArea: ["Dining & Island", "Living Room", "Foyer"],
    styleTheme: "Warm Minimalist",
    warmthOptions: ["2700K Warm White", "3000K Soft Warm"],
    finishes: ["Brushed Solid Brass", "Aged Antique Brass", "Burnished Bronze"],
    images: [
      "/images/prod-h2001.png",
      "/images/hero-1.jpg",
      "/images/prod-vintage-1.jpg",
    ],
    dimensions: "Dia: 120cm x H: 4.5cm | Adjustable Suspension Cable: 200cm max",
    leadTime: "3 to 4 Weeks (Handcrafted to order)",
    craftsmanshipNotes:
      "Forged in our Jaipur atelier. Custom drop lengths and brass patina finishes available upon trade request.",
    specSheetUrl: "#download-spec",
    isFeatured: true,
    heroHotspot: { x: 35, y: 40 },
  },
  {
    id: "prod-2",
    slug: "imperial-grand-chandelier",
    title: "Imperial Grand Chandelier",
    tagline: "Multi-tiered mouth-blown glass flutes suspended from a sculpted brass chassis.",
    description:
      "A monumental centerpiece designed for double-height ceilings, entry foyers, and luxury dining spaces. Features 24 individual mouth-blown clear glass flutes held in place by precision-machined solid brass arms.",
    fixtureType: "Chandeliers",
    spatialArea: ["Living Room", "Foyer", "Outdoor/Hospitality"],
    styleTheme: "Sculptural Glass",
    warmthOptions: ["2700K Warm White", "2200K Candlelight Warm"],
    finishes: ["Aged Antique Brass", "Brushed Solid Brass", "Hand-Blown Smoked Glass"],
    images: [
      "/images/prod-ch1001.png",
      "/images/prod-ch1002.png",
      "/images/hero-2.jpg",
    ],
    dimensions: "Dia: 140cm x H: 180cm | Total Weight: 42 kg",
    leadTime: "5 to 6 Weeks",
    craftsmanshipNotes:
      "Mouth-blown glass flutes crafted by master glassblowers. Each piece displays subtle organic bubbles unique to artisan glasswork.",
    specSheetUrl: "#download-spec",
    isFeatured: true,
    heroHotspot: { x: 65, y: 25 },
  },
  {
    id: "prod-3",
    slug: "vanguard-brutalist-sconce",
    title: "Vanguard Brutalist Sconce",
    tagline: "Hand-hammered heavy brass facade casting ambient indirect backlight.",
    description:
      "Inspired by mid-century architectural brutalism, the Vanguard Sconce features a thick brass plate with raw textured surfaces. Light escapes from behind the facade, bathing adjacent walls in a soft, low-glare golden aura.",
    fixtureType: "Sconces",
    spatialArea: ["Foyer", "Living Room", "Bedside"],
    styleTheme: "Brutalist Brass",
    warmthOptions: ["2200K Candlelight Warm", "2700K Warm White"],
    finishes: ["Burnished Bronze", "Aged Antique Brass", "Brushed Solid Brass"],
    images: [
      "/images/prod-vintage-2.jpg",
      "/images/prod-vintage-3.jpg",
    ],
    dimensions: "W: 24cm x H: 50cm x D: 9cm",
    leadTime: "2 to 3 Weeks",
    craftsmanshipNotes:
      "Textured through manual hammer strikes. Surface patinas naturally over time unless requested polished.",
    specSheetUrl: "#download-spec",
    isFeatured: true,
  },
  {
    id: "prod-4",
    slug: "aurora-monolith-surface-mount",
    title: "Aurora Monolith Surface Mount",
    tagline: "Ultra-thin ceiling fixture with integrated diffused opal diffuser.",
    description:
      "Designed for rooms requiring high lumen output without sacrificing ceiling height. The Aurora Monolith pairs a spun brass outer rim with high-CRI 95+ LED technology for vibrant color rendering.",
    fixtureType: "Surface/Flush",
    spatialArea: ["Bedside", "Foyer", "Outdoor/Hospitality"],
    styleTheme: "Warm Minimalist",
    warmthOptions: ["2700K Warm White", "3000K Soft Warm"],
    finishes: ["Brushed Solid Brass", "Polished Chrome", "Aged Antique Brass"],
    images: [
      "/images/prod-vintage-4.jpg",
      "/images/hero-3.jpg",
    ],
    dimensions: "Dia: 60cm x Projection: 5.5cm",
    leadTime: "2 Weeks",
    craftsmanshipNotes: "Dimmable via standard TRIAC or 0-10V architectural dimming drivers.",
    specSheetUrl: "#download-spec",
    isFeatured: false,
  },
  {
    id: "prod-5",
    slug: "solstice-architectural-floor-lamp",
    title: "Solstice Architectural Floor Lamp",
    tagline: "Slender brass stem with a counterweighted smoked glass globe.",
    description:
      "A harmonious study in balance and proportion. The Solstice floor lamp features a solid turned brass base, tactile rotary dimmer knob, and a hand-blown smoked charcoal glass dome.",
    fixtureType: "Table & Floor",
    spatialArea: ["Living Room", "Bedside"],
    styleTheme: "Sculptural Glass",
    warmthOptions: ["2700K Warm White", "3000K Soft Warm"],
    finishes: ["Hand-Blown Smoked Glass", "Brushed Solid Brass", "Burnished Bronze"],
    images: [
      "/images/prod-tl3001.png",
      "/images/hero-3.jpg",
    ],
    dimensions: "Base Dia: 32cm x H: 175cm",
    leadTime: "3 Weeks",
    craftsmanshipNotes: "Includes integrated weighted marble stabilizer inside turned brass pedestal.",
    specSheetUrl: "#download-spec",
    isFeatured: true,
  },
];

export const MOCK_CLIENT_LOGOS = [
  { name: "Fairmont Hotels & Resorts", category: "Luxury Resort", location: "Jaipur", logoUrl: "/images/logo-fairmont.svg" },
  { name: "Raffles Hotels & Resorts", category: "Palatial Heritage", location: "Global", logoUrl: "/images/logo-raffles.svg" },
  { name: "ITC Hotels", category: "Luxury Heritage", location: "Jaipur", logoUrl: "/images/logo-itc.svg" },
  { name: "Taj Hotels Group", category: "Heritage Hotels", location: "Worldwide", logoUrl: "/images/logo-taj.svg" },
  { name: "Oberoi Hotels & Resorts", category: "Luxury Hospitality", location: "International", logoUrl: "/images/logo-oberoi.svg" },
  { name: "Hilton Hotels & Resorts", category: "International Hospitality", location: "Worldwide", logoUrl: "/images/logo-hilton.svg" },
  { name: "Studio Lotus", category: "Architects", location: "New Delhi", logoUrl: "/images/logo-studiolotus.svg" },
  { name: "Morphogenesis", category: "Architects & Masterplanners", location: "Global", logoUrl: "/images/logo-morphogenesis.svg" },
  { name: "Khosla Associates", category: "Architecture & Interiors", location: "Bengaluru", logoUrl: "/images/logo-khosla.svg" },
  { name: "Ashiesh Shah Atelier", category: "Interior Architecture", location: "Mumbai", logoUrl: "/images/logo-ashieshshah.svg" },
];

export const MOCK_PROJECTS: ProjectCaseStudy[] = [
  {
    id: "proj-1",
    slug: "fairmont-jaipur",
    title: "Fairmont Jaipur",
    subtitle: "Monumental brass chandeliers and grand ballroom spatial installations reflecting Mughal grandeur.",
    category: "Hospitality & Dining",
    location: "Jaipur, Rajasthan",
    clientArchitect: "Fairmont Hotels & Resorts",
    coverImage: "/images/proj-1.jpg",
    gallery: ["/images/proj-1.jpg", "/images/hero-1.jpg", "/images/hero-2.jpg"],
    description: "Custom multi-tiered hand-burnished solid brass chandeliers and grand corridor lantern sconces engineered for the majestic palace ballrooms and atriums.",
    taggedFixtureSlugs: ["imperial-grand-chandelier", "vanguard-brutalist-sconce"],
    isFeatured: true,
  },
  {
    id: "proj-2",
    slug: "raffles-udaipur",
    title: "Raffles Udaipur",
    subtitle: "Palatial island estate luminaires blending classical European romance with Rajasthani metalwork.",
    category: "Hospitality & Dining",
    location: "Udaipur, Rajasthan",
    clientArchitect: "Raffles Hotels & Private Estates",
    coverImage: "/images/hero-2.jpg",
    gallery: ["/images/hero-2.jpg", "/images/proj-2.jpg"],
    description: "Atmospheric custom chandeliers, mouth-blown glass wall sconces, and private suite luminaires installed across the private island sanctuary.",
    taggedFixtureSlugs: ["imperial-grand-chandelier", "astra-halo-pendant"],
    isFeatured: true,
  },
  {
    id: "proj-3",
    slug: "umaid-bhawan-palace",
    title: "Umaid Bhawan Palace",
    subtitle: "Art Deco and heritage royal luminaire restorations and bespoke presidential suite lighting.",
    category: "Hospitality & Dining",
    location: "Jodhpur, Rajasthan",
    clientArchitect: "Taj Hotels & Royal Family of Jodhpur",
    coverImage: "/images/proj-3.jpg",
    gallery: ["/images/proj-3.jpg", "/images/hero-3.jpg"],
    description: "Hand-crafted heritage sconces and Art Deco-inspired polished brass architectural pendants tailored to the world-renowned golden sandstone palace.",
    taggedFixtureSlugs: ["vanguard-brutalist-sconce", "aurora-monolith-surface-mount"],
    isFeatured: true,
  },
  {
    id: "proj-4",
    slug: "suryagarh-jaisalmer",
    title: "Suryagarh Jaisalmer",
    subtitle: "Fortress-inspired deep patina lanterns and golden hour courtyard lighting compositions.",
    category: "Hospitality & Dining",
    location: "Jaisalmer, Rajasthan",
    clientArchitect: "Suryagarh Heritage Collection",
    coverImage: "/images/hero-1.jpg",
    gallery: ["/images/hero-1.jpg", "/images/proj-1.jpg"],
    description: "Raw sand-cast and acid-patinated brass lighting installations designed to complement the Thar Desert golden limestone architecture.",
    taggedFixtureSlugs: ["imperial-grand-chandelier", "solstice-architectural-floor-lamp"],
    isFeatured: true,
  },
  {
    id: "proj-5",
    slug: "villa-palladio-jaipur",
    title: "Villa Palladio",
    subtitle: "Romantic, theatrical crimson and hand-rubbed brass luminaires for an iconic boutique estate.",
    category: "Hospitality & Dining",
    location: "Jaipur, Rajasthan",
    clientArchitect: "Studio Lotus & Ashiesh Shah Atelier",
    coverImage: "/images/hero-3.jpg",
    gallery: ["/images/hero-3.jpg", "/images/proj-2.jpg"],
    description: "Bespoke custom brass candelabras, low-lit corridor wall brackets, and dining veranda pendants creating a timeless, atmospheric retreat.",
    taggedFixtureSlugs: ["vanguard-brutalist-sconce", "astra-halo-pendant"],
    isFeatured: true,
  },
  {
    id: "proj-6",
    slug: "city-palace-jaipur",
    title: "City Palace Jaipur",
    subtitle: "Historic courtyard and royal audience hall bespoke lighting and restoration.",
    category: "Private Residences",
    location: "Jaipur, Rajasthan",
    clientArchitect: "Royal Family of Jaipur Atelier",
    coverImage: "/images/proj-2.jpg",
    gallery: ["/images/proj-2.jpg", "/images/hero-1.jpg"],
    description: "Restored and newly commissioned ceremonial chandeliers and museum-grade solid brass wall sconces illuminating royal galleries and courtyards.",
    taggedFixtureSlugs: ["imperial-grand-chandelier", "aurora-monolith-surface-mount"],
    isFeatured: true,
  },
  {
    id: "proj-7",
    slug: "udai-vilas-palace-udaipur",
    title: "Udai Vilas Palace",
    subtitle: "Lakeside palace promenade lighting and gold-leafed royal dome luminaires.",
    category: "Hospitality & Dining",
    location: "Udaipur, Rajasthan",
    clientArchitect: "Oberoi Luxury Heritage",
    coverImage: "/images/hero-2.jpg",
    gallery: ["/images/hero-2.jpg"],
    description: "Custom lighting schedules featuring weather-sealed solid brass promenade lamps and grand dining rotunda chandeliers.",
    taggedFixtureSlugs: ["imperial-grand-chandelier"],
    isFeatured: false,
  },
  {
    id: "proj-8",
    slug: "raffles-jaipur",
    title: "Raffles Jaipur",
    subtitle: "Bespoke hand-carved white marble and burnished brass luminaires for luxury suites.",
    category: "Hospitality & Dining",
    location: "Jaipur, Rajasthan",
    clientArchitect: "Raffles Hotels International",
    coverImage: "/images/hero-1.jpg",
    gallery: ["/images/hero-1.jpg"],
    description: "Sculptural lighting installations blending heritage Rajasthani craftsmanship with modern French neoclassical luxury.",
    taggedFixtureSlugs: ["astra-halo-pendant"],
    isFeatured: false,
  },
  {
    id: "proj-9",
    slug: "alsisar-haveli",
    title: "Alsisar Haveli",
    subtitle: "Intricate traditional haveli courtyard and heritage suite spatial illumination.",
    category: "Hospitality & Dining",
    location: "Jaipur, Rajasthan",
    clientArchitect: "Alsisar Hotels & Heritage",
    coverImage: "/images/proj-1.jpg",
    gallery: ["/images/proj-1.jpg"],
    description: "Custom filigree lanterns and antique brass sconces installed throughout the historic 18th-century Rajput haveli.",
    taggedFixtureSlugs: ["vanguard-brutalist-sconce"],
    isFeatured: false,
  },
  {
    id: "proj-10",
    slug: "nahargarh-ranthambore",
    title: "Nahargarh Ranthambore",
    subtitle: "Aristocratic hunting lodge fortress lighting nestled in the wild forest foothills.",
    category: "Hospitality & Dining",
    location: "Ranthambore, Rajasthan",
    clientArchitect: "Alsisar Heritage Group",
    coverImage: "/images/proj-3.jpg",
    gallery: ["/images/proj-3.jpg"],
    description: "Monumental outdoor brass torches, central courtyard chandeliers, and vintage glass lantern pendants.",
    taggedFixtureSlugs: ["imperial-grand-chandelier"],
    isFeatured: false,
  },
  {
    id: "proj-11",
    slug: "shahpura-house-jaipur",
    title: "Shahpura House",
    subtitle: "Shekhawati-style frescoed ceilings framed by warm architectural luminaires.",
    category: "Hospitality & Dining",
    location: "Jaipur, Rajasthan",
    clientArchitect: "Shahpura Heritage Hotels",
    coverImage: "/images/hero-3.jpg",
    gallery: ["/images/hero-3.jpg"],
    description: "Custom brass hanging fixtures and indirect warm LED perimeter lighting highlighting historic gold leaf murals.",
    taggedFixtureSlugs: ["aurora-monolith-surface-mount"],
    isFeatured: false,
  },
  {
    id: "proj-12",
    slug: "itc-jaipur-jaisalmer",
    title: "ITC Rajputana & ITC Jaisalmer",
    subtitle: "Grand heritage lobby chandeliers and presidential suite architectural lighting.",
    category: "Hospitality & Dining",
    location: "Jaipur & Jaisalmer",
    clientArchitect: "ITC Luxury Collection",
    coverImage: "/images/proj-1.jpg",
    gallery: ["/images/proj-1.jpg"],
    description: "Signature bespoke lighting collections tailored for high-volume luxury hospitality and grand banqueting suites.",
    taggedFixtureSlugs: ["imperial-grand-chandelier", "vanguard-brutalist-sconce"],
    isFeatured: false,
  },
  {
    id: "proj-13",
    slug: "noor-mahal-karnal",
    title: "Noor Mahal Palace",
    subtitle: "Opulent royal palace banquet hall chandeliers and regal colonnade sconces.",
    category: "Hospitality & Dining",
    location: "Karnal, Haryana",
    clientArchitect: "Noor Mahal Heritage",
    coverImage: "/images/hero-2.jpg",
    gallery: ["/images/hero-2.jpg"],
    description: "Custom large-scale solid brass chandeliers exceeding 3.5 meters in diameter crafted for monumental ballroom ceilings.",
    taggedFixtureSlugs: ["imperial-grand-chandelier"],
    isFeatured: false,
  },
  {
    id: "proj-14",
    slug: "laxmi-vilas-palace-bharatpur",
    title: "Laxmi Vilas Palace",
    subtitle: "1857 royal palace heritage suites and courtyard lantern installations.",
    category: "Hospitality & Dining",
    location: "Bharatpur, Rajasthan",
    clientArchitect: "Laxmi Vilas Heritage",
    coverImage: "/images/hero-1.jpg",
    gallery: ["/images/hero-1.jpg"],
    description: "Hand-aged antique brass luminaires and custom glass globe pendants illuminating historic verandahs and suites.",
    taggedFixtureSlugs: ["vanguard-brutalist-sconce"],
    isFeatured: false,
  },
  {
    id: "proj-15",
    slug: "hyatt-regency-mansarovar",
    title: "Hyatt Regency Mansarovar",
    subtitle: "Modern architectural lighting with subtle artisanal brass touches.",
    category: "Commercial & Retail",
    location: "Jaipur, Rajasthan",
    clientArchitect: "Hyatt Hotels Corporation",
    coverImage: "/images/proj-2.jpg",
    gallery: ["/images/proj-2.jpg"],
    description: "Contemporary linear architectural pendants and custom lobby atrium fixtures tailored to international hospitality standards.",
    taggedFixtureSlugs: ["astra-halo-pendant"],
    isFeatured: false,
  },
  {
    id: "proj-16",
    slug: "umaid-resort",
    title: "Umaid Resort",
    subtitle: "Palatial landscaped gardens and private poolside villa ambient lighting.",
    category: "Hospitality & Dining",
    location: "Rajasthan",
    clientArchitect: "Umaid Group",
    coverImage: "/images/hero-3.jpg",
    gallery: ["/images/hero-3.jpg"],
    description: "Bespoke outdoor bollards, courtyard lantern sconces, and dining canopy pendants.",
    taggedFixtureSlugs: ["solstice-architectural-floor-lamp"],
    isFeatured: false,
  },
  {
    id: "proj-17",
    slug: "reliance-jio-ltd",
    title: "Reliance Jio Corporate HQ",
    subtitle: "Monumental executive boardroom chandeliers and private corporate suite lighting.",
    category: "Commercial & Retail",
    location: "Mumbai, Maharashtra",
    clientArchitect: "Reliance Industries Ltd",
    coverImage: "/images/proj-3.jpg",
    gallery: ["/images/proj-3.jpg"],
    description: "High-precision architectural linear luminaires and statement brass installations for executive boardrooms and VIP reception halls.",
    taggedFixtureSlugs: ["astra-halo-pendant", "aurora-monolith-surface-mount"],
    isFeatured: false,
  },
];

export const MOCK_STORIES: Story[] = [
  {
    id: "story-1",
    slug: "craftsmanship-brass-patina",
    title: "The Art of Hand-Burnished Brass",
    subtitle: "Why heavy-gauge solid brass is the beating heart of Parashar Lighting.",
    category: "Craftsmanship",
    image: "/images/hero-1.jpg",
    content: [
      "At Parashar Lighting, brass is not merely a material choice—it is a living canvas. We exclusively source solid architectural-grade brass free from cast impurities.",
      "Our artisans in Jaipur utilize centuries-old metalworking techniques combined with precise CNC tolerances. Each surface is hand-patinated using custom organic acid baths, producing rich, luminous tones from warm honey champagne to deep burnished oil-rubbed bronze.",
      "Rather than applying cheap synthetic lacquers that chip or yellow, we hand-wax every finished brass luminaire with natural bees-wax sealer. This allows the metal to age gracefully, acquiring character alongside your space.",
    ],
    quote: "True luxury is felt in the weight of solid brass and seen in the quiet depth of a hand-applied patina.",
  },
  {
    id: "story-2",
    slug: "sculptural-glass-blowing",
    title: "Mouth-blown Glass & Warmth Ratings",
    subtitle: "Precision optics meet organic artisan glasscrafting.",
    category: "Finishes",
    image: "/images/hero-3.jpg",
    content: [
      "Every glass component in our Sculptural collection is individually mouth-blown by master glass artisans. No two flutes or globes are identical—each carries subtle, organic micro-eddies that gently refract light.",
      "We pair our artisan glass shades with custom-engineered 95+ CRI LED engines rated strictly at 2200K, 2700K, and 3000K warmth levels. This eliminates unflattering harsh blue light, replacing it with a restorative golden ambience.",
    ],
    quote: "We don't just illuminate rooms—we paint spatial atmospheres in warm kelvin gradients.",
  },
  {
    id: "story-3",
    slug: "custom-spatial-engineering",
    title: "Bespeak Architectural Scale & Custom Lead Times",
    subtitle: "Tailored drop lengths, custom diameters, and dedicated trade support.",
    category: "Custom Capabilities",
    image: "/images/hero-2.jpg",
    content: [
      "We partner directly with architects, interior designers, and hospitality project managers. Every fixture in our catalog can be customized in drop length, overall diameter, wattage output, and control protocols (DALI, 0-10V, Casambi).",
      "Our trade desk handles custom shop drawings, photometric IES files, and sample finish kits, with standard lead times ranging between 2 to 5 weeks.",
    ],
    quote: "No two architectural spaces are identical. Our workshop exists to turn spatial drawings into real illumination.",
  },
];
